apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: argocd-applicationset-controller-placementdecision
subjects:
- kind: ServiceAccount
  name: argocd-applicationset-controller
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-applicationset-controller-placementdecision
  apiGroup: rbac.authorization.k8s.io