apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
  name: infra-all
  namespace: argocd
spec:
  destination:
    name: local-cluster
    namespace: argocd
  project: default
  source:
    repoURL: git@github.com:Kuadrant/api-poc-setup.git
    targetRevision: main
    path: .
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true