---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
  name: rhsso
  namespace: argocd
spec:
  destination:
    name: local-cluster
    namespace: rhsso
  project: infra
  source:
    repoURL: git@github.com:Kuadrant/api-poc-setup.git
    targetRevision: main
    path: resources/rhsso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
