apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.12.2
    releaseName: mgc
    namespace: cert-manager
    valuesInline:
      global:
        leaderElection:
          namespace: cert-manager
      installCRDs: true
      # Customize active controllers
      extraArgs: ["--controllers=*,-ingress-shim","--enable-certificate-owner-ref=true"]
